# see: https://golangci-lint.run/usage/configuration/ for config info
run:
  # default concurrency is a available CPU number
  concurrency: 10
  # include test files or not, default is true
  tests: true
  # lint examples
  skip-dirs-use-default: false
  # for slow ci machines
  timeout: 10m

linters-settings:
  golint:
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  disable:
    # Global variables are used in many places throughout the code base.
    - gochecknoglobals

    # Some lines are over 80 characters on purpose and we don't want to make them
    # even longer by marking them as 'nolint'.
    - lll

    # We don't care (enough) about misaligned structs to lint that.
    - maligned

    # We have long functions, especially in tests. Moving or renaming those would
    # trigger funlen problems that we may not want to solve at that time.
    - funlen

    # Disable for now as we haven't yet tuned the sensitivity to our codebase
    # yet.  Enabling by default for example, would also force new contributors to
    # potentially extensively refactor code, when they want to smaller change to
    # land.
    - gocyclo

    # Instances of table driven tests that don't pre-allocate shouldn't trigger
    # the linter.
    - prealloc

    # Init functions are used by loggers throughout the codebase.
    - gochecknoinits
    # we want TODO's in code for now
    - godox

    # this messes with our interface checks
    - exhaustivestruct

    # interfacer is deprecated
    - interfacer
  enable-all: true
  fast: false


issues:
  exclude-use-default: false

  # Only show newly introduced problems.
  new-from-rev: 1e3f118f3a37112432d00a717d500949926e87ca