name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    if: "!contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        platform: [ubuntu-latest]
        # TODO add mac os here
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Linters
        run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2"
      - name: Test
        run: ./goclean.sh
      - name: Build
        env:
          GO111MODULE: "on"
        run: go build ./...

  test:
    if: "!contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    strategy:
      matrix:
         go-version: [1.15.x, 1.16.x]
         platform: [ubuntu-latest]
         # TODO add mac os here
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install go-acc
        shell: bash
        run: go get -u github.com/ory/go-acc
        env:
          GO111MODULE: "on"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Linters
        run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2"
      - name: Test
        run: env GORACE="halt_on_error=1" go-acc -o profile.cov -race ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-profile: profile.cov
      - name: Build
        env:
          GO111MODULE: "on"
        run: go build ./...
